using Godot;
using StrikeLedger.Core;
using StrikeLedger.App;

public partial class Main
{
    TrainingSession? lab;
    void StartLab(){lab=new TrainingSession(content,fighter[0],$"art_{art[0]+1}",77);sim=lab.Simulation;fighter[1]=sim.Config.Fighter1;recorder=null;mode="training";drillIndex=0;ResetLabDrill(lab.Drill.Id);trainingMode=lab.DummyMode.ToString();paused=false;Clear("fight");inputGrace=12;}
    void TickLab(){if(lab==null||sim==null)return;var sample=input.Sample(0,sim.Tick);if(inputGrace>0){inputGrace--;sample=new(0,sim.Tick,5,Buttons.None);}var result=lab.FrameAdvance(sample.Direction,sample.Held);lastInputs[0]=sample;var frame=lab.Recording.LastOrDefault();lastInputs[1]=frame==null?new(1,sim.Tick,5,Buttons.None):new(1,frame.Tick,frame.Direction1,frame.Buttons1);string line=$"{sample.Direction} {sample.Held}";if(inputHistory[0].Count==0||inputHistory[0].Last()!=line){inputHistory[0].Enqueue(line);while(inputHistory[0].Count>9)inputHistory[0].Dequeue();}TrackLabContact(result);ObserveChanges(result);}
    void LabMenu(){paused=true;Clear("labmenu");Heading("Training controls",lab?.Drill.Title.ToUpperInvariant()??"TRAINING",lab?.Feedback??"");Button("Resume →",55,189,555,Resume,true);Button("Single frame →",665,189,560,()=>{TickLab();Clear("fight");paused=true;});Button("Reset drill",55,249,555,()=>{ResetLabDrill(lab!.Drill.Id);sim=lab.Simulation;Resume();});Button("Next drill →",665,249,560,()=>{drillIndex=(drillIndex+1)%TrainingSession.Drills.Length;ResetLabDrill(TrainingSession.Drills[drillIndex].Id);LabMenu();});Button("Swap sides",55,309,555,()=>{lab!.SwapSides();Resume();});Button("Hitboxes: "+(debugBoxes?"on":"off"),665,309,560,()=>{debugBoxes=!debugBoxes;LabMenu();});Button("Save checkpoint",55,369,555,()=>{lab!.SaveCheckpoint();LabMenu();});Button("Restore checkpoint",665,369,560,()=>{lab!.RestoreCheckpoint();Resume();});Button(lab?.RecordingDummy==true?"Stop dummy recording":"Record dummy (control P2)",55,429,555,()=>{if(lab!.RecordingDummy)lab.EndDummyRecording();else lab.BeginDummyRecording();Resume();});Button("Loop recorded dummy",665,429,560,()=>{lab!.PlayDummyRecording();Resume();});Button("Move list",55,489,555,()=>MoveList(0));Button("Dummy: "+(lab?.DummyMode.ToString()??"Passive"),665,489,560,()=>{var modes=new[]{BotMode.Passive,BotMode.Guard,BotMode.Jump,BotMode.Throw,BotMode.Conservative,BotMode.Adaptive};lab!.DummyMode=modes[(Array.IndexOf(modes,lab.DummyMode)+1)%modes.Length];trainingMode=lab.DummyMode.ToString();LabMenu();});Button("Training wallet: "+(sim?.Players[0].Credits??0)+" CR ↔",55,549,555,()=>{sim!.SetTrainingState(0,credits:sim.Players[0].Credits>=3600?0:sim.Players[0].Credits+300);LabMenu();});Button("State & speed →",665,549,560,LabStateMenu);Button("Export drill trace",665,600,560,()=>{lab!.ExportRecording(ProjectSettings.GlobalizePath("user://training/latest.json"));Toast("Drill trace saved.");});Back(Title);}
}
