using Godot;
using StrikeLedger.Core;
using StrikeLedger.App;
using StrikeLedger.Presentation;
using System.Text.Json;

public partial class Main
{
    void Clear(string next){screen=next;screenTime=0;if(next=="fight")input.SuppressHeldButtons();if(computerEvidence)Capture(next+"-"+DateTime.Now.ToString("HHmmss"));foreach(var child in ui.GetChildren())child.QueueFree();statusLabel=null;arena.Visible=true;}
    Label Text(string text,float x,float y,int size=20,Color? color=null,float width=0){var l=new Label{Text=text,Position=new(x,y),MouseFilter=Control.MouseFilterEnum.Ignore};l.AddThemeFontSizeOverride("font_size",size);l.AddThemeColorOverride("font_color",color??Cream);if(width>0){l.Size=new(width,0);l.AutowrapMode=TextServer.AutowrapMode.WordSmart;}ui.AddChild(l);return l;}
    void Panel(float x,float y,float w,float h,Color? color=null){ui.AddChild(new ColorRect{Position=new(x,y),Size=new(w,h),Color=color??new Color(.045f,.075f,.1f,.95f),MouseFilter=Control.MouseFilterEnum.Ignore});}
    Button Button(string text,float x,float y,float w,Action action,bool first=false,int size=22){var b=new Button{Text=text,Position=new(x,y),Size=new(w,44),Alignment=HorizontalAlignment.Left,FocusMode=Control.FocusModeEnum.All};b.AddThemeFontSizeOverride("font_size",size);b.AddThemeColorOverride("font_color",Cream);b.AddThemeColorOverride("font_hover_color",Ink);b.AddThemeColorOverride("font_focus_color",Gold);StyleBoxFlat Box(Color c,Color border)=>new(){BgColor=c,BorderColor=border,BorderWidthBottom=1,ContentMarginLeft=16,ContentMarginRight=12};b.AddThemeStyleboxOverride("normal",Box(new Color(.065f,.1f,.13f,.96f),new Color(.2f,.28f,.31f)));b.AddThemeStyleboxOverride("hover",Box(Gold,Gold));b.AddThemeStyleboxOverride("pressed",Box(new Color(.25f,.31f,.33f),Gold));b.AddThemeStyleboxOverride("focus",new StyleBoxFlat{BgColor=Colors.Transparent,BorderColor=Gold,BorderWidthLeft=3,BorderWidthRight=1,BorderWidthTop=1,BorderWidthBottom=1});b.Pressed+=()=>{arena.PlayCue("menu");action();};ui.AddChild(b);if(first)b.CallDeferred(Control.MethodName.GrabFocus);return b;}
    void Heading(string eyebrow,string title,string subtitle=""){Panel(0,0,1280,720,new Color(.025f,.045f,.06f,.93f));Text(eyebrow.ToUpperInvariant(),54,30,16,Gold);Text(title,52,61,46);if(subtitle!="")Text(subtitle,56,122,18,Muted,1160);}
    void Back(Action? action=null){Button("← Back",54,648,180,action??Title);Text("ARROWS / D-PAD  navigate     ENTER / A  select     ESC / B  back",262,screen=="select"?702:659,14,Muted);}
    void IdleScene(){arena.SetState(new ArenaRenderState{Tick=(int)(Time.GetTicksMsec()/16),Fighters=new[]{new FighterRenderState{Id="rook",X=315000,Palette=0,Facing=1},new FighterRenderState{Id="vale",X=465000,Palette=1,Facing=-1}}});}
    void Title(){peer?.Dispose();peer=null;sim=null;recorder=null;replay=null;paused=false;Clear("title");IdleScene();Panel(0,0,665,720,new Color(.025f,.045f,.06f,.96f));Text("THE FOUNDRY CIRCUIT / 01",56,35,16,Gold);Text("STRIKE",48,68,91);Text("LEDGER",48,154,91,Gold);Text("EVERY ROUND HAS A PRICE.",57,266,19,Muted);Button("01   Versus CPU",56,321,420,()=>Select("bot"),true);Button("02   Local versus",56,372,420,()=>Select("local"));Button("03   Training lab",56,423,420,()=>Select("training"));Button("04   Private match",56,474,420,NetworkMenu);Button("Replays",56,535,202,ReplayMenu,false,18);Button("Settings",274,535,202,SettingsMenu,false,18);Button("Field manual",56,586,202,Help,false,18);Button("Quit",274,586,202,()=>QuitGame(),false,18);Text("2 FIGHTERS / 6 BUTTONS / ONE WALLET",56,672,14,Muted);Text("ORIGINAL 1V1 FIGHTING",831,643,15,Muted);}
    void Select(string nextMode){mode=nextMode;Clear("select");Heading("Choose your corner",mode=="training"?"TRAINING LAB":"THE LINEUP","One fighter. One super. Locked for the match. Ordinary attacks and defense stay free.");for(int s=0;s<2;s++){int seat=s;float x=54+s*608;Panel(x,173,570,445);Text(s==0?"01 / YOUR CORNER":mode=="bot"?"02 / CPU OPPONENT":"02 / OPPOSING CORNER",x+22,187,16,s==0?Gold:Cyan);Button(fighter[s].ToUpperInvariant()+"  ↔",x+20,222,526,()=>{fighter[seat]=fighter[seat]=="rook"?"vale":"rook";Select(mode);},s==0,30);Text(fighter[s]=="rook"?"Motion / pressure / close-range confirms":"Charge / spacing / long-reaching kicks",x+23,282,17,Muted);var arts=fighterJson[fighter[s]].GetProperty("super_arts").EnumerateArray().ToArray();for(int n=0;n<3;n++){int a=n;var info=arts[n];Button($"{(art[s]==n?"●":"○")}  {info.GetProperty("name").GetString()} / {info.GetProperty("credit_cost")} CR",x+20,326+n*61,526,()=>{art[seat]=a;Select(mode);},false,20);Text(info.GetProperty("role").GetString()!.Replace('_',' '),x+39,372+n*61,13,Muted);}Button("Device: "+(mode=="bot"&&s==1?"CPU":input.DeviceName(s)),x+20,544,526,()=>{CycleDevice(seat);Select(mode);},false,16);}if(mode=="bot")Button("CPU: "+cpuPolicy+" ↔",550,648,350,()=>{cpuPolicy=cpuPolicy==BotMode.Adaptive?BotMode.Conservative:BotMode.Adaptive;Select(mode);},false,18);Back();Button(mode=="training"?"Enter lab →":"Start match →",918,648,308,()=>{if(mode=="local"&&(input.Devices[0]<-1||input.Devices[1]<-1)){Toast("Assign keyboard + controller, or two controllers.");return;}StartMatch();});}
    void CycleDevice(int seat){var ids=new List<int>{-1,-2};ids.AddRange(input.ConnectedDevices);int pos=ids.IndexOf(input.Devices[seat]);for(int n=1;n<=ids.Count;n++)if(input.Assign(seat,ids[(pos+n)%ids.Count]))break;}
    JsonElement[] ItemsFor(int seat)=>items.EnumerateArray().Where(i=>i.GetProperty("eligible_fighters").EnumerateArray().Any(v=>v.GetString()==fighter[seat])).ToArray();
    string[] DraftItems(int seat){var list=ItemsFor(seat);return draft[seat].Select((v,slot)=>v<0?null:list[slot*2+v].GetProperty("id").GetString()).Where(x=>x!=null).Select(x=>x!).ToArray();}
    int DraftCost(int seat)=>draft[seat].Select((v,slot)=>v<0?0:slot==0?900:slot==1?600:300).Sum();
    void Preparation(bool reset=true){if(sim==null)return;if(reset){draft=new[]{new[]{-1,-1,-1},new[]{-1,-1,-1}};floor=new[]{0,0};ready=new[]{false,mode is "bot" or "demo"};prepTicks=900;if(mode is "bot" or "demo")SetCpuDraft();}Clear("prep");Heading("Round preparation","SPEND. SAVE. COMMIT.","Leases last one round. EX costs 300 at startup. Your selected super uses the same wallet.");for(int s=0;s<2;s++){int seat=s;float x=54+s*608;Panel(x,168,570,453);var p=sim.Players[s];Text($"{s+1:00} / {fighter[s].ToUpperInvariant()}",x+20,179,20,s==0?Gold:Cyan);Text($"{p.Credits:N0} CR",x+362,176,28);var list=ItemsFor(s);for(int slot=0;slot<3;slot++){int sl=slot;Text(new[]{"SIGNATURE / 900","TECHNIQUE / 600","GAMBIT / 300"}[slot],x+20,222+slot*87,13,Muted);int selected=draft[s][slot];string name=selected<0?"Keep base kit · 0 CR":list[slot*2+selected].GetProperty("name").GetString()!;Button(name+" ↔",x+20,247+slot*87,526,()=>{if(ready[seat])return;draft[seat][sl]=(draft[seat][sl]+2)%3-1;Preparation(false);},false,18);Text(LeasePreview(s,slot,selected),x+24,291+slot*87,11,Muted);}Button($"Reserve floor: {floor[s]} CR ↔",x+20,509,526,()=>{if(ready[seat])return;CycleAffordableReserve(seat);Preparation(false);},false,16);int left=p.Credits-DraftCost(s);Text($"After lock: {left} CR / Win: {Math.Min(3600,left+1200)} / Loss: {Math.Min(3600,left+new[]{900,1200,1500}[Math.Min(2,p.RecoveryTier)])}",x+22,561,16,left>=floor[s]?Muted:new Color("f0796e"));Text("Projection assumes no further combat spending.",x+22,587,13,Muted);}statusLabel=Text("",475,650,17,Gold);Button(ready[0]?"P1 locked ✓":"P1 ready",54,648,258,()=>ReadyPlan(0),true);Button(ready[1]?"P2 locked ✓":"P2 ready",970,648,258,()=>ReadyPlan(1));RefreshPreparationFocus();}
    void ReadyPlan(int s){if(sim==null||ready[s])return;if(sim.Players[s].Credits-DraftCost(s)<floor[s]){Toast("Plan exceeds wallet or reserve. Remove a lease or lower floor.");return;}ready[s]=true;Preparation(false);if(ready.All(v=>v))LockPlans();}
    void LockPlans(){if(sim==null)return;for(int s=0;s<2;s++)if(sim.Players[s].Credits-DraftCost(s)<floor[s]){draft[s]=new[]{-1,-1,-1};floor[s]=0;}try{var p0=new PreparationPlan(DraftItems(0),floor[0]);var p1=new PreparationPlan(DraftItems(1),floor[1]);if(recorder!=null)recorder.CommitPreparation(sim,p0,p1,$"prep-{sim.RoundId}");else sim.CommitPreparation(p0,p1);Clear("fight");inputGrace=18;arena.PlayCue("round");}catch(Exception e){Toast(e.Message);ready=new[]{false,false};Preparation(false);}}
    void FinishMatch(){SaveReplay();Clear("results");Heading("Final settlement","THE BOOKS ARE CLOSED.");if(sim==null)return;string result=sim.Players[0].ScoreHalfPoints==sim.Players[1].ScoreHalfPoints?"MATCH DRAW":sim.Players[0].ScoreHalfPoints>sim.Players[1].ScoreHalfPoints?fighter[0].ToUpperInvariant()+" WINS":fighter[1].ToUpperInvariant()+" WINS";Text(result,56,199,55,Gold);for(int i=0;i<2;i++)Text($"{fighter[i].ToUpperInvariant()} / {sim.Players[i].ScoreHalfPoints/2f:0.#} points / {sim.Players[i].Credits} CR",58,310+i*62,30);Text("Replay saved locally. Credits reset when a new match begins.",58,473,20,Muted);Button("Run it back →",56,551,405,()=>{if(peer!=null){peer.Dispose();peer=null;NetworkMenu();}else StartMatch();},true);Button("Change lineup",486,551,320,()=>{if(peer!=null){peer.Dispose();peer=null;NetworkMenu();}else Select(mode);});Back();if(smoke){Capture("match-result");evidenceLog?.WriteLine($"MATCH COMPLETE {sim.Hash()}");evidenceLog?.Flush();CallDeferred(nameof(CompleteSmoke));}}
    void PauseMenu(){if(mode=="replay"){ReplayControls();return;}if(mode=="training"){LabMenu();return;}if(peer!=null)peer.Pause();paused=true;Clear("pause");Heading("Time out","PAUSED");Button("Resume →",55,192,460,Resume,true);Button("Move list",55,247,460,()=>MoveList(0));Button("Controls & device test",55,302,460,ControlsMenu);Button("Settings",55,357,460,SettingsMenu);Button("Save replay",55,412,460,()=>{SaveReplay();Toast("Replay saved.");});Button("Return to title",55,467,460,Title);}
    void Resume(){if(peer!=null)peer.Resume();Clear("fight");paused=false;inputGrace=12;}
    void Help(){Clear("help");Heading("Field manual","YOUR BASE KIT IS ALWAYS FREE.");Text("MOVE / A D walk. W jump. S crouch. Double-tap to dash.\nGUARD / Hold away. Down-away blocks lows. No air block.\nPARRY / Tap toward for high/air attacks, down for lows.\nATTACK / U I O = light, medium, heavy punches. J K L = kicks.\nTHROW / LP + LK. OVERHEAD / MP + MK. PP / P. KK / semicolon.\nMOTIONS / QCF = down, down-toward, toward. DP = toward, down, down-toward.\nCHARGE / Hold away or down for 45 ticks, then opposite + attack.\nEX / Finish a special motion with two punches or kicks.\nSUPER / Double QCF + required attack. See the move list.",58,177,22,Cream,1160);Text("THE ECONOMY\nStart with 600 CR. EX spends 300 on startup; supers spend 900 / 1200 / 1500.\nWin: +1200. Loss: +900 / 1200 / 1500 by recovery tier. Draw: +900. Cap: 3600.\nShop techniques and paid moves share one wallet. Combat never earns credits.\nLeases last one round. Your reserve prevents spending below a chosen floor.",58,459,20,Gold,1160);Back();Button("Move list →",948,648,278,()=>MoveList(0));}
    void MoveList(int seat,int page=0){Clear("moves");Heading("Command reference",fighter[seat].ToUpperInvariant()+" / MOVE LIST","Relative directions. PP/KK requires two fresh buttons on one tick. Frames = startup / active / recovery.");var moves=fighterJson[fighter[seat]].GetProperty("moves").EnumerateArray().ToArray();for(int row=0;row<12&&page*12+row<moves.Length;row++){var m=moves[page*12+row];float y=180+row*35;Text(m.GetProperty("name").GetString()!,55,y,18);Text(m.GetProperty("command").GetString()!,391,y,17,Gold);Text($"{m.GetProperty("startup")} / {m.GetProperty("active")} / {m.GetProperty("recovery")}",762,y,17,Muted);Text(m.TryGetProperty("credit_cost",out var cost)?cost+" CR":"FREE",1032,y,17,Cyan);}Back(sim!=null?PauseMenu:Title);Button("Other fighter",400,648,230,()=>MoveList(1-seat));Button($"Page {page+1}/5 →",945,648,280,()=>MoveList(seat,(page+1)%5));}
    void SettingsMenu(){Clear("settings");Heading("Preferences","MAKE YOURSELF AT HOME.");void Slider(string name,float val,float y,Action<float> set){Text(name,56,y+7,22);var s=new HSlider{Position=new(338,y),Size=new(530,42),MinValue=0,MaxValue=1,Step=.05,Value=val};s.ValueChanged+=v=>{set((float)v);settings.Save();arena.SetVolumes(settings.Master,settings.Music,settings.Sfx);};ui.AddChild(s);}Slider("Master volume",settings.Master,185,v=>settings.Master=v);Slider("Music",settings.Music,245,v=>settings.Music=v);Slider("Sound effects",settings.Sfx,305,v=>settings.Sfx=v);Button("Flashes: "+(settings.ReducedFlashes?"reduced":"full"),56,378,390,()=>{settings.ReducedFlashes=!settings.ReducedFlashes;settings.Save();SettingsMenu();},true);Button("Camera shake: "+(settings.Shake?"on":"off"),467,378,390,()=>{settings.Shake=!settings.Shake;settings.Save();SettingsMenu();});Button("Display: "+(settings.Fullscreen?"fullscreen":"windowed"),56,436,390,()=>{settings.Fullscreen=!settings.Fullscreen;settings.Apply();settings.Save();SettingsMenu();});Button("VSync: "+(settings.Vsync?"on":"off"),467,436,390,()=>{settings.Vsync=!settings.Vsync;settings.Apply();settings.Save();SettingsMenu();});Button("Resolution: "+settings.Width+" × "+settings.Width*9/16,56,494,390,()=>{settings.Width=settings.Width==1280?1600:settings.Width==1600?1920:1280;settings.Apply();settings.Save();SettingsMenu();});Button("Controls & remapping →",467,494,390,ControlsMenu);Text("Visual preferences never change simulation timing.",56,570,18,Muted);Back(sim!=null?PauseMenu:Title);}
    void ControlsMenu(){Clear("controls");Heading("Input workshop","TWO INDEPENDENT CORNERS.","Opposite directions resolve neutral. PP/KK are simultaneous chords; motions stay manual.");for(int s=0;s<2;s++){int seat=s;Button($"P{s+1} / {input.DeviceName(s)} ↔",55+s*607,173,570,()=>{CycleDevice(seat);ControlsMenu();},s==0,19);}string[] names={"Left","Right","Up","Down","LP","MP","HP","LK","MK","HK","PP","KK"};for(int i=0;i<12;i++){int idx=i;Button($"{names[i]} / {OS.GetKeycodeString((Key)settings.Keys[i])}",55+(i%4)*294,246+(i/4)*61,279,()=>{remapIndex=idx;remapDevice=-1;captureBinding=true;Toast("Press a physical key for "+names[idx]);},false,18);}BuildPadRemapControls(names);Button($"Stick deadzone: {settings.Deadzone:P0} ↔",55,572,360,()=>{settings.Deadzone=settings.Deadzone>=.6f?.15f:settings.Deadzone+.05f;settings.Save();ControlsMenu();},false,18);statusLabel=Text("",450,583,17,Cyan);Back(sim!=null?PauseMenu:SettingsMenu);}
    void SaveReplay(){if(peer!=null){try{string path=ProjectSettings.GlobalizePath("user://replays/private-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".json");peer.SaveReplay(path);ExportEconomyFiles(path,ReplayFormat.Load(path,content.ContentHash));}catch(Exception ex){Toast("Private replay: "+ex.Message);}return;}if(recorder==null)return;try{string dir=ProjectSettings.GlobalizePath("user://replays");System.IO.Directory.CreateDirectory(dir);string path=System.IO.Path.Combine(dir,"match-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".json");recorder.Save(path);ExportEconomyFiles(path,recorder.Record);if(smoke)recorder.Save(System.IO.Path.Combine(evidenceDir,"full-match.replay.json"));}catch(Exception e){Toast("Replay: "+e.Message);}}
    void ReplayMenu(){Clear("replays");Heading("Match archive","RUN THE TAPE.","Recorded inputs and confirmed transactions. Playback verifies deterministic state and wallets.");string dir=ProjectSettings.GlobalizePath("user://replays");System.IO.Directory.CreateDirectory(dir);var files=System.IO.Directory.GetFiles(dir,"*.json").Where(p=>!p.EndsWith(".economy.json")).OrderDescending().Take(8).ToArray();if(files.Length==0)Text("Completed and saved matches appear here.",56,206,24,Muted);for(int n=0;n<files.Length;n++){string f=files[n];Button(System.IO.Path.GetFileNameWithoutExtension(f),56,190+n*53,1165,()=>{try{var record=ReplayFormat.Load(f,content.ContentHash);activeReplayRecord=record;replay=new ReplayPlayer(content,record);mode="replay";sim=replay.Simulation;fighter=new[]{sim.Config.Fighter0,sim.Config.Fighter1};art=new[]{int.Parse(sim.Config.Super0.AsSpan(4))-1,int.Parse(sim.Config.Super1.AsSpan(4))-1};recorder=null;Clear("fight");}catch(Exception e){Toast("Replay rejected: "+e.Message);}},n==0,19);}Back();}
    void NetworkMenu(){Clear("network_menu");Heading("Direct connection","PRIVATE 1V1.","Trusted LAN or existing private link. Both peers must use the same build and lineup.");Text("Opponent IP",56,199,22);var address=new LineEdit{Text=networkAddress,Position=new(340,190),Size=new(596,48)};address.TextChanged+=v=>networkAddress=v;ui.AddChild(address);Button("Edit with pad",965,190,260,()=>PadTextEditor("Opponent IP",networkAddress,v=>networkAddress=v,true),false,18);Text("UDP base port",56,266,22);var port=new LineEdit{Text=networkPort,Position=new(340,257),Size=new(250,48)};port.TextChanged+=v=>networkPort=v;ui.AddChild(port);Button("Edit with pad",965,257,260,()=>PadTextEditor("UDP base port",networkPort,v=>networkPort=v,true),false,18);Text("Match phrase",56,333,22);var code=new LineEdit{Text=networkCode,Position=new(340,324),Size=new(596,48)};code.TextChanged+=v=>networkCode=v;ui.AddChild(code);Button("Edit with pad",965,324,260,()=>PadTextEditor("Match phrase",networkCode,v=>networkCode=v),false,18);for(int s=0;s<2;s++){int seat=s;Button($"P{s+1}: {fighter[s]} / art {art[s]+1} ↔",56+s*590,403,570,()=>{art[seat]=(art[seat]+1)%3;if(art[seat]==0)fighter[seat]=fighter[seat]=="rook"?"vale":"rook";NetworkMenu();},false,19);}Button("Host / P1 →",56,490,418,()=>StartNetwork(true),true);Button("Join / P2 →",502,490,418,()=>StartNetwork(false));Text("Two-frame input delay with rollback. No account needed.\nHost listens on the base port; join listens on base port + 1.\nBoth players enter their opponent’s IP and the same phrase.",56,550,17,Muted);Back();}
}
