using Godot;
using StrikeLedger.Core;
using StrikeLedger.App;
using StrikeLedger.Presentation;
using System.Text.Json;

public partial class Main
{
    void Clear(string next){screen=next;screenTime=0;if(next=="fight")input.SuppressHeldButtons();if(computerEvidence)Capture(next+"-"+DateTime.Now.ToString("HHmmss"));foreach(var child in ui.GetChildren())child.QueueFree();statusLabel=null;arena.Visible=true;}
    Label Text(string text,float x,float y,int size=20,Color? color=null,float width=0){var l=new Label{Text=text,Position=new(x,y),MouseFilter=Control.MouseFilterEnum.Ignore};l.AddThemeFontSizeOverride("font_size",size);l.AddThemeColorOverride("font_color",color??Cream);if(width>0){l.Size=new(width,0);l.AutowrapMode=TextServer.AutowrapMode.WordSmart;}ui.AddChild(l);return l;}
    void Panel(float x,float y,float w,float h,Color? color=null)=>UiArtPanel(x,y,w,h,color);
    Button Button(string text,float x,float y,float w,Action action,bool first=false,int size=22){var b=new Button{Text=text,Position=new(x,y),Size=new(w,44),Alignment=HorizontalAlignment.Left,FocusMode=Control.FocusModeEnum.All};b.AddThemeFontSizeOverride("font_size",size);UiSkinButton(b);b.Pressed+=()=>{arena.PlayCue("menu");action();};ui.AddChild(b);if(first)b.CallDeferred(Control.MethodName.GrabFocus);return b;}
    void Heading(string eyebrow,string title,string subtitle=""){UiArtBackdrop();Text(eyebrow.ToUpperInvariant(),54,30,16,Gold);Text(title,52,61,46).AddThemeFontOverride("font",UiTypography.Heading);if(subtitle!="")Text(subtitle,56,122,18,Muted,1160);UiScreenIcon();}
    void Back(Action? action=null){Button("← Back",54,648,180,action??Title);Text("ARROWS / D-PAD  navigate     ENTER / A  select     ESC / B  back",262,702,14,Muted);}
    void IdleScene(){arena.SetState(new ArenaRenderState{StageId=stageId,Tick=(int)(Time.GetTicksMsec()/16),Fighters=new[]{new FighterRenderState{Id="rook",X=315000,Palette=0,Facing=1},new FighterRenderState{Id="vale",X=465000,Palette=1,Facing=-1}}});}
    void Title(){LeavePrivateMatch();sim=null;recorder=null;replay=null;paused=false;Clear("title");IdleScene();UiArtBackdrop(true);Text("AFTER HOURS / THE FOUNDRY CIRCUIT",56,27,14,Muted);UiArtWordmark();Button("01   Versus CPU",56,321,420,()=>Select("bot"),true);Button("02   Local versus",56,372,420,()=>Select("local"));Button("03   Training lab",56,423,420,()=>Select("training"));Button("04   Private match",56,474,420,NetworkMenu);Button("Replays",56,535,202,ReplayMenu,false,18);Button("Settings",274,535,202,SettingsMenu,false,18);Button("Field manual",56,586,202,Help,false,18);Button("Quit",274,586,202,()=>QuitGame(),false,18);Text($"{content.Fighters.Count} FIGHTERS / {content.Stages.Count} STAGES / ONE WALLET",56,674,14,Muted);Text("THE CIRCUIT OPENS AFTER HOURS",844,679,13,Cream);}
    void CycleDevice(int seat){var ids=new List<int>{-1,-2};ids.AddRange(input.ConnectedDevices);int pos=ids.IndexOf(input.Devices[seat]);for(int n=1;n<=ids.Count;n++)if(input.Assign(seat,ids[(pos+n)%ids.Count]))break;}
    void FinishMatch(){var saved=SaveReplay();Clear("results");Heading("Final settlement","THE BOOKS ARE CLOSED.");if(sim==null)return;string result=sim.Players[0].ScoreHalfPoints==sim.Players[1].ScoreHalfPoints?"MATCH DRAW":sim.Players[0].ScoreHalfPoints>sim.Players[1].ScoreHalfPoints?FighterName(fighter[0]).ToUpperInvariant()+" WINS":FighterName(fighter[1]).ToUpperInvariant()+" WINS";UiPortraitPanel(sim.Players[0].ScoreHalfPoints>=sim.Players[1].ScoreHalfPoints?fighter[0]:fighter[1],new Rect2(920,184,270,283));Text(result,56,199,55,Gold);for(int i=0;i<2;i++)Text($"{FighterName(fighter[i]).ToUpperInvariant()} / {sim.Players[i].ScoreHalfPoints/2f:0.#} points / {sim.Players[i].Credits} CR",58,310+i*62,30);Text(saved.Message+". New matches reset credits.",58,473,18,Muted,840);Button("Run it back →",56,551,405,()=>{if(peer!=null)RequestPrivateRematch();else StartMatch();},true);Button("Change lineup",486,551,320,()=>{if(peer!=null){LeavePrivateMatch("Change lineup");NetworkMenu();}else Select(mode);});Back();if(smoke){Capture("match-result");evidenceLog?.WriteLine($"MATCH COMPLETE {sim.Hash()}");evidenceLog?.Flush();CallDeferred(nameof(CompleteSmoke));}}
    void PauseMenu(){if(mode=="replay"){ReplayControls();return;}if(mode=="training"){LabMenu();return;}if(peer!=null)peer.Pause();paused=true;Clear("pause");Heading("Time out",peer?.Status==PeerStatus.Pausing?"PAUSING…":"PAUSED",peer?.Status==PeerStatus.Pausing?peer.Diagnostic:"");Button("Resume →",55,192,460,Resume,true);Button("Move list",55,247,460,()=>MoveList(0));Button("Controls & device test",55,302,460,ControlsMenu);Button("Settings",55,357,460,SettingsMenu);Button("Save replay",55,412,460,()=>Toast(SaveReplay().Message));Button("Return to title",55,467,460,Title);}
    void Resume(){if(peer?.Status==PeerStatus.Pausing){Toast("Waiting for both peers to reach the pause boundary.");return;}if(peer!=null)peer.Resume();Clear("fight");paused=false;inputGrace=12;}
    void Help()
    {
        Clear("help");Heading("Field manual","YOUR BASE KIT IS ALWAYS FREE.");
        Text("MOVE / A D walk. W jump. S crouch. Double-tap to dash.\nGUARD / Hold away. Down-away blocks lows. No air block.\nPARRY / Tap toward for high/air attacks, down for lows.\nATTACK / U I O = light, medium, heavy punches. J K L = kicks.\nTHROW / LP + LK. OVERHEAD / MP + MK. PP / P. KK / semicolon.\nMOTIONS / QCF = down, down-toward, toward. DP = toward, down, down-toward.\nCHARGE / Hold away or down, then opposite + attack. See the command list.\nEX / Finish a special motion with two fresh punches or kicks together.\nSUPER / Buy one use in the shop. Double QCF + the purchased art’s attack.",58,177,21,Cream,1160);
        var money=content.Economy;
        Text($"THE ECONOMY\nStart {money.StartingCredits} CR. Shop only: rentals, up to two repeatable EX licenses, one optional super use.\nWin +{money.WinPayout}. Loss +{string.Join(" / ",money.LossPayouts)} by recovery tier. Draw +{money.DrawPayout}. Cap {money.Cap}.\nCounter-hits, anti-airs and perfect parries earn capped rewards for the NEXT SHOP.\nBank stays fixed during combat. Equipment expires each round. Rematches reset money.",58,454,20,Gold,1160);
        Back();Button("Rental catalog",655,648,260,()=>RentalCatalog(0),false,18);Button("Move list →",948,648,278,()=>MoveList(0));
    }

    string CommandAccessLabel(string fighterId,string moveId)
    {
        var move=content.Fighters[fighterId].Move(moveId);var item=content.Items.Values.FirstOrDefault(i=>i.EligibleFighters.Contains(fighterId)&&i.MoveId==moveId);
        return item==null?move.DerivedFrom.Length>0?"OWNED BRANCH":"FREE BASE":item.Slot=="super"?"SHOP / ONE USE":item.Slot=="ex"?"SHOP / EX LICENSE":"SHOP / RENTAL";
    }
    void MoveList(int seat,int page=0){Clear("moves");Heading("Command reference",FighterName(fighter[seat]).ToUpperInvariant()+" / MOVE LIST","Relative directions. PP/KK requires two fresh buttons on one tick. Frames = startup / active / recovery.");var moves=fighterJson[fighter[seat]].GetProperty("moves").EnumerateArray().ToArray();for(int row=0;row<12&&page*12+row<moves.Length;row++){var m=moves[page*12+row];float y=180+row*35;Text(m.GetProperty("name").GetString()!,55,y,18);Text(m.GetProperty("command").GetString()!,391,y,17,Gold);Text($"{m.GetProperty("startup")} / {m.GetProperty("active")} / {m.GetProperty("recovery")}",762,y,17,Muted);Text(CommandAccessLabel(fighter[seat],m.GetProperty("id").GetString()!),1032,y,15,Cyan);}Back(sim!=null?PauseMenu:Title);Button("Other fighter",400,648,230,()=>MoveList(1-seat));Button($"Page {page+1}/{(moves.Length+11)/12} →",945,648,280,()=>MoveList(seat,(page+1)%((moves.Length+11)/12)));}
    void SettingsMenu(){Clear("settings");Heading("Preferences","MAKE YOURSELF AT HOME.");void Slider(string name,float val,float y,Action<float> set){Text(name,56,y+7,22);var s=new HSlider{Position=new(338,y),Size=new(530,42),MinValue=0,MaxValue=1,Step=.05,Value=val};s.ValueChanged+=v=>{set((float)v);settings.Save();arena.SetVolumes(settings.Master,settings.Music,settings.Sfx);};ui.AddChild(s);}Slider("Master volume",settings.Master,185,v=>settings.Master=v);Slider("Music",settings.Music,245,v=>settings.Music=v);Slider("Sound effects",settings.Sfx,305,v=>settings.Sfx=v);Button("Flashes: "+(settings.ReducedFlashes?"reduced":"full"),56,378,390,()=>{settings.ReducedFlashes=!settings.ReducedFlashes;settings.Save();SettingsMenu();},true);Button("Camera shake: "+(settings.Shake?"on":"off"),467,378,390,()=>{settings.Shake=!settings.Shake;settings.Save();SettingsMenu();});Button("Display: "+(settings.Fullscreen?"fullscreen":"windowed"),56,436,390,()=>{settings.Fullscreen=!settings.Fullscreen;settings.Apply();settings.Save();SettingsMenu();});Button("VSync: "+(settings.Vsync?"on":"off"),467,436,390,()=>{settings.Vsync=!settings.Vsync;settings.Apply();settings.Save();SettingsMenu();});Button("Resolution: "+settings.Width+" × "+settings.Width*9/16,56,494,390,()=>{settings.Width=settings.Width==1280?1600:settings.Width==1600?1920:1280;settings.Apply();settings.Save();SettingsMenu();});Button("Controls & remapping →",467,494,390,ControlsMenu);Button("Keyboard: "+settings.KeyboardLayoutMode+" layout ↔",56,552,801,()=>{settings.KeyboardLayoutMode=settings.KeyboardLayoutMode=="Physical"?"Logical":"Physical";settings.Save();SettingsMenu();},false,18);Text("Physical binds key positions. Logical follows the selected language layout.",56,610,17,Muted);Back(sim!=null?PauseMenu:Title);}
    void ControlsMenu(){Clear("controls");Heading("Input workshop","TWO INDEPENDENT CORNERS.","Opposite directions resolve neutral. PP/KK are simultaneous chords; motions stay manual.");for(int s=0;s<2;s++){int seat=s;Button($"P{s+1} / {input.DeviceName(s)} ↔",55+s*607,173,570,()=>{CycleDevice(seat);ControlsMenu();},s==0,19);}string[] names={"Left","Right","Up","Down","LP","MP","HP","LK","MK","HK","PP","KK"};for(int i=0;i<12;i++){int idx=i;Button($"{names[i]} / {OS.GetKeycodeString((Key)settings.Keys[i])}",55+(i%4)*294,246+(i/4)*61,279,()=>{remapIndex=idx;remapDevice=-1;captureBinding=true;Toast("Press a physical key for "+names[idx]);},false,18);}BuildPadRemapControls(names);Button($"Stick deadzone: {settings.Deadzone:P0} ↔",55,572,360,()=>{settings.Deadzone=settings.Deadzone>=.6f?.15f:settings.Deadzone+.05f;settings.Save();ControlsMenu();},false,18);statusLabel=Text("",450,583,17,Cyan);Back(sim!=null?PauseMenu:SettingsMenu);}
}
