using Godot;
using StrikeLedger.App;
public partial class Main
{
    double replayAccumulator;bool showWalletGraph,showReplayInputs=true,showReplayReceipts=true;ReplayRecord? activeReplayRecord;
    void AdvanceReplay(){if(replay==null)return;replayAccumulator+=replay.Speed;while(replayAccumulator>=1){replayAccumulator--;if(!replay.FrameAdvance()){paused=true;Toast("End of verified replay. Open the replay controls to seek.");break;}ObserveChanges();}}
    void ReplayControls(){paused=true;Clear("replay_controls");Heading("Playback controls","FOLLOW THE MONEY.","Seek restores the simulation, wallet, and confirmed transactions together.");Button("Resume →",55,191,555,Resume,true);Button("Frame advance",665,191,555,()=>{replay!.FrameAdvance();ObserveChanges();Clear("fight");paused=true;});Button("Back 5 seconds",55,251,555,()=>{replay!.Seek(Math.Max(0,sim!.Tick-300));Resume();});Button("Forward 5 seconds",665,251,555,()=>{replay!.Seek(sim!.Tick+300);Resume();});Button("Restart replay",55,311,555,()=>{replay!.Seek(0);Resume();});Button($"Speed {replay?.Speed:0.0}× ↔",665,311,555,()=>{replay!.Speed=replay.Speed==.5?1:replay.Speed==1?2:.5;ReplayControls();});Button("Wallet graph: "+(showWalletGraph?"on":"off"),55,371,555,()=>{showWalletGraph=!showWalletGraph;ReplayControls();});Button("Replay archive",665,371,555,ReplayMenu);Button("Inputs: "+(showReplayInputs?"on":"off"),55,431,555,()=>{showReplayInputs=!showReplayInputs;ReplayControls();});Button("Hitboxes: "+(debugBoxes?"on":"off"),665,431,555,()=>{debugBoxes=!debugBoxes;ReplayControls();});Button("Spend receipts: "+(showReplayReceipts?"on":"off"),55,491,555,()=>{showReplayReceipts=!showReplayReceipts;ReplayControls();});Button("Export round economy",665,491,555,()=>{if(activeReplayRecord!=null){ExportEconomyFiles(ProjectSettings.GlobalizePath("user://replays/economy-export.json"),activeReplayRecord);Toast("Economy JSON, CSV and round table exported.");}});Text("The graph displays the recorded credit balance. It is not an earned combat gauge.",55,569,20,Muted,1160);Back(Title);}
    void DrawReplayOverlay(){if(mode!="replay"||replay==null)return;DrawString(font,new(38,653),$"REPLAY / {replay.Speed:0.0}× / TICK {sim?.Tick} / {(paused?"PAUSED":"VERIFIED PLAYBACK")}",HorizontalAlignment.Left,-1,15,Gold);DrawReplayDetails();if(!showWalletGraph)return;var graph=replay.WalletGraph;if(graph.Count<2)return;DrawRect(new Rect2(740,452,500,183),new Color(.025f,.045f,.06f,.92f));long max=Math.Max(1,graph[^1].Tick);for(int seat=0;seat<2;seat++){for(int i=1;i<graph.Count;i++){var a=graph[i-1];var b=graph[i];int ca=seat==0?a.Seat0:a.Seat1,cb=seat==0?b.Seat0:b.Seat1;DrawLine(new Vector2(756+(float)a.Tick/max*464,612-ca/3600f*130),new Vector2(756+(float)b.Tick/max*464,612-cb/3600f*130),seat==0?Gold:Cyan,2);}}DrawString(font,new(756,478),"RECORDED WALLET / 0–3600 CR",HorizontalAlignment.Left,-1,13,Cream);}
}
