using Godot;
using StrikeLedger.Core;
using StrikeLedger.App;
public partial class Main
{
    double labAccumulator;int comboDamage,lastComboDamage;long firstFree0=-1,firstFree1=-1;int? advantage;bool measuringContact;string parsedCommand="No command yet";
    void ResetLabDrill(string id){if(lab==null)return;if(id=="charge_side_switch"&&fighter[0]!="vale")lab=new TrainingSession(content,"vale",$"art_{art[0]+1}",77);lab.Reset(id);trainingMode=lab.DummyMode.ToString();sim=lab.Simulation;fighter[0]=sim.Config.Fighter0;fighter[1]=sim.Config.Fighter1;comboDamage=0;lastComboDamage=0;measuringContact=false;advantage=null;parsedCommand="Follow the drill instructions";}
    void TrackLabContact(StepResult result){if(sim==null)return;foreach(var e in result.Events){if(e.Seat==0&&e.Kind is CombatEventKind.ActionStarted or CombatEventKind.Rejected)parsedCommand=e.Kind==CombatEventKind.Rejected?$"DENIED {e.MoveId}: {e.Detail}":$"PARSED {e.MoveId}";if(e.Kind==CombatEventKind.Hit&&e.Seat==0){comboDamage+=e.Value;measuringContact=true;firstFree0=firstFree1=-1;}if(e.Kind==CombatEventKind.Block&&e.Target==0){measuringContact=true;firstFree0=firstFree1=-1;}}
        if(measuringContact){if(firstFree0<0&&sim.Players[0].Actionable)firstFree0=sim.Tick;if(firstFree1<0&&sim.Players[1].Actionable)firstFree1=sim.Tick;if(firstFree0>=0&&firstFree1>=0){advantage=(int)(firstFree1-firstFree0);measuringContact=false;lastComboDamage=comboDamage;comboDamage=0;}}}
    void LabStateMenu(){paused=true;Clear("lab_state");Heading("Training-only state","SET THE SITUATION.","These controls exist only in the training simulation. Competitive matches reject them.");for(int seat=0;seat<2;seat++){int s=seat;float x=55+seat*609;var p=sim!.Players[s];Text($"P{s+1} / {p.FighterId.ToUpperInvariant()}",x,180,28,s==0?Gold:Cyan);Button($"Health {p.Health} ↔",x,234,557,()=>{sim.SetTrainingState(s,health:p.Health>=1000?100:p.Health+100);LabStateMenu();},seat==0);Button($"Stun {p.Stun} ↔",x,297,557,()=>{sim.SetTrainingState(s,stun:p.Stun>=900?0:p.Stun+100);LabStateMenu();});Button($"Credits {p.Credits} ↔",x,360,557,()=>{sim.SetTrainingState(s,credits:p.Credits>=3600?0:p.Credits+300);LabStateMenu();});Button("Position: left / center / right ↔",x,423,557,()=>{sim.SetTrainingState(s,x:p.X<100000?384000:p.X<600000?720000:48000);LabStateMenu();},false,19);}Button($"Simulation speed {lab!.Speed:0.00}× ↔",55,504,555,()=>{lab.Speed=lab.Speed==1?.5:lab.Speed==.5?.25:1;LabStateMenu();});Button("Return to practice →",664,504,557,Resume);Back(LabMenu);}
}
